fixed to print the message into stderr.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -38,7 +38,7 @@ then
   echo "Configuring for $OS..."
   aix
 else
-  echo "OS $OS not supported, aborting..." 1&>2
+  echo "OS $OS not supported, aborting..." >&2
   exit 1
 fi
 
